import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import type { ReactNode } from "react";

import { Header } from "@/components/Header";
import { LayoutProvider } from "@/contexts/layout";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  pageTitle,
}: Readonly<{
  children: React.ReactNode;
  pageTitle: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LayoutProvider>
          <Header />
          <h1 className="border-solid border-2 border-green-500">
            {pageTitle || "NemoDreaming"}
          </h1>
          {children}
        </LayoutProvider>
      </body>
    </html>
  );
}
